name: Ping Solid Ground AZ Site

on:
  schedule:
    # Run every 10 minutes except 1-3 AM AZ time (8-10 AM UTC)
    - cron: '*/10 0-7 * * *'
    - cron: '*/10 10-23 * * *'

jobs:
  ping-site:
    name: GET https://solidgroundaz.site/
    runs-on: ubuntu-latest
    steps:
      - name: Ping website
        run: |
          curl -f https://solidgroundaz.site/ || exit 1
        timeout-minutes: 5

